port: 9000

release:
  public: /Users/mkrogh/writeurl/build/release/browser

debug:
  host: debug.writeurl.localhost
  public: /Users/mkrogh/writeurl/build/debug/browser

documents:
  path: /Users/mkrogh/writeurl-test-dir/doc_dir

publish:
  public: /Users/mkrogh/writeurl-test-dir/publish_dir

# Pino logger
# Output goes to stdout.
logger:
  # levels: silent, fatal, error, warn, info, debug, trace
  level: trace

# virtual hosts for other web sites shared with Writeurl.
virtual_hosts:
  - host: amberbio.localhost
    public: /Users/mkrogh/writeurl-test-dir/amberbio
